name: Terraform Deploy Strapi ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./task9

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./task9

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./task9

      - name: Build Docker Image
        run: docker build -t strapi-app ./my-strapi-app

      - name: Push Docker Image to ECR (optional)
        if: false  # Set to true and configure ECR if needed
        run: echo "Push step here"
